# -*- coding: utf-8 -*-
"""ev3_ HIT140_Ass2_S395783.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6W_MrTjo1ZjsjfDFNGmTbcZBnaUSFbk
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive/"

!ls "/content/drive/MyDrive/HIT140_Foundation Of data Science/"

file_path_dataset1 = "/content/drive/MyDrive/HIT140_Foundation Of data Science/dataset1.csv"

file_path_dataset2 = "/content/drive/MyDrive/HIT140_Foundation Of data Science/dataset2.csv"
df_dataset2 = pd.read_csv(file_path_dataset2)
print(df_dataset2.head())

"""Dataset 2 time 30 min interval to 1min."""

import pandas as pd

# Converting 'time' column in datetime frame
df_dataset2['time'] = pd.to_datetime(df_dataset2['time'], format='%d/%m/%Y %H:%M')


expanded_rows = []

for idx, row in df_dataset2.iterrows():

    times = pd.date_range(start=row['time'], periods=30, freq='T')  # 'T' = 1 minute
    for t in times:
        new_row = row.copy()
        new_row['time'] = t
        expanded_rows.append(new_row)


df_dataset2_expanded = pd.DataFrame(expanded_rows)


df_dataset2_expanded.reset_index(drop=True, inplace=True)


print(df_dataset2_expanded.head(35))
print("Expanded dataset shape:", df_dataset2_expanded.shape)



df_dataset1 = pd.read_csv(file_path_dataset1)
print(df_dataset1.head())

file_path_dataset2 = "/content/drive/MyDrive/HIT140_Foundation Of data Science/dataset2.csv"
df_dataset2 = pd.read_csv(file_path_dataset2)
print(df_dataset2.head())

import pandas as pd


df_dataset1['start_time'] = pd.to_datetime(df_dataset1['start_time'], format='%d/%m/%Y %H:%M')
df_dataset2_expanded['time'] = pd.to_datetime(df_dataset2_expanded['time'])

# --- Merge datasets: left merge ---
merged_df = pd.merge(
    df_dataset1,
    df_dataset2_expanded,
    left_on='start_time',
    right_on='time',
    how='left'
)


print(merged_df.head(10))
print("Merged dataset shape:", merged_df.shape)

from google.colab import files


output_file_path = "merged_dataset.xlsx"
merged_df.to_excel(output_file_path, index=False)


files.download(output_file_path)

# food availability to food categorization
threshold = merged_df['food_availability'].median()

merged_df['food_category'] = merged_df['food_availability'].apply(
    lambda x: "High Food" if x > threshold else "Low Food"
)

print(merged_df['food_category'].value_counts())

print(merged_df[['food_availability', 'food_category']].head(10))

"""Chi Square Test"""

import pandas as pd
from scipy.stats import chi2_contingency


contingency_table = pd.crosstab(merged_df['food_category'], merged_df['risk'])
print("Contingency Table:")
print(contingency_table)

chi2, p, dof, expected = chi2_contingency(contingency_table)

print("\nChi-square Test Result:")
print(f"Chi2 statistic: {chi2:.4f}")
print(f"p-value: {p:.4f}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(pd.DataFrame(expected, index=contingency_table.index, columns=contingency_table.columns))

"""Visualization of Chi square test"""

import seaborn as sns
import matplotlib.pyplot as plt


plt.figure(figsize=(6,5))
sns.heatmap(contingency_table, annot=True, fmt="d", cmap="Blues", cbar=False)
plt.title("Observed Counts: Food Availability vs Risk-Taking")
plt.xlabel("Risk (0=Avoid, 1=Take)")
plt.ylabel("Food Availability Category")
plt.show()


expected_df = pd.DataFrame(expected, index=contingency_table.index, columns=contingency_table.columns)
plt.figure(figsize=(6,5))
sns.heatmap(expected_df, annot=True, fmt=".1f", cmap="Oranges", cbar=False)
plt.title("Expected Counts (Chi-square assumption)")
plt.xlabel("Risk (0=Avoid, 1=Take)")
plt.ylabel("Food Availability Category")
plt.show()

"""  T-tests: compare rewards across High vs Low Food."""

import pandas as pd
from scipy.stats import ttest_ind


reward_risk = merged_df[merged_df['risk'] == 1]['reward']
reward_avoid = merged_df[merged_df['risk'] == 0]['reward']


t_stat, p_value = ttest_ind(reward_risk, reward_avoid, equal_var=False)  # Welch's t-test
print("T-test: Reward for Risk-Takers vs Risk-Avoiders")
print(f"T-statistic = {t_stat:.4f}, p-value = {p_value:.4f}")


for category in merged_df['food_category'].unique():
    group = merged_df[merged_df['food_category'] == category]
    reward_risk = group[group['risk'] == 1]['reward']
    reward_avoid = group[group['risk'] == 0]['reward']
    t_stat, p_value = ttest_ind(reward_risk, reward_avoid, equal_var=False)
    print(f"\nT-test for {category}: Reward Risk vs Avoid")
    print(f"T-statistic = {t_stat:.4f}, p-value = {p_value:.4f}")

import seaborn as sns
import matplotlib.pyplot as plt


plt.figure(figsize=(7,5))
sns.barplot(data=merged_df, x='risk', y='reward', hue='food_category', ci='sd')
plt.xticks([0,1], ['Avoid Risk (0)', 'Take Risk (1)'])
plt.ylabel('Average Reward')
plt.xlabel('Risk Behavior')
plt.title('Average Reward for Risk-Avoiders vs Risk-Takers by Food Category')
plt.legend(title='Food Category')
plt.show()

"""Visualization of t test"""

import pandas as pd
import matplotlib.pyplot as plt


stack_data = merged_df.groupby(['food_category', 'risk'])['reward'].sum().unstack()


stack_data.plot(kind='bar', stacked=True, figsize=(8,6), color=['blue','red'])

plt.xlabel('Food Category')
plt.ylabel('Total Reward')
plt.title('Stacked Bar Chart: Reward by Risk Behavior and Food Category')
plt.legend(title='Risk Behavior', labels=['Avoid Risk (0)','Take Risk (1)'])
plt.show()

"""Logistic Regression"""

import pandas as pd
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

X = merged_df[['reward']]
y = merged_df['risk']


X = sm.add_constant(X)

logit_model = sm.Logit(y, X)
result = logit_model.fit()

print(result.summary())


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


logit_model_skl = sm.Logit(y_train, X_train).fit()

y_pred_prob = logit_model_skl.predict(X_test)

y_pred = (y_pred_prob >= 0.5).astype(int)


print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_pred_prob))

"""Logistic Regression Visualization"""

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

X = sm.add_constant(merged_df['reward'])
y = merged_df['risk']


logit_model = sm.Logit(y, X).fit(disp=0)


x_range = np.linspace(merged_df['reward'].min(), merged_df['reward'].max(), 300)
X_range = sm.add_constant(x_range)


y_prob = logit_model.predict(X_range)


plt.figure(figsize=(8,6))
plt.plot(x_range, y_prob, color='red', linewidth=2, label='Probability of Taking Risk')


plt.fill_between(x_range, y_prob, 0, color='blue', alpha=0.2, label='Avoid Risk Zone (More Reward)')

plt.axhline(0.5, color='gray', linestyle='--', linewidth=1)

plt.xlabel('Reward')
plt.ylabel('Risk')
plt.title('Logistic Regression Curve: Reward vs Risk-Taking')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

plt.figure(figsize=(8,6))

for category, color in zip(['High Food', 'Low Food'], ['blue', 'green']):
    df_cat = merged_df[merged_df['food_category'] == category]


    X = sm.add_constant(df_cat['reward'])
    y = df_cat['risk']
    model = sm.Logit(y, X).fit(disp=0)


    x_range = np.linspace(df_cat['reward'].min(), df_cat['reward'].max(), 300)
    X_range = sm.add_constant(x_range)
    y_prob = model.predict(X_range)


    plt.plot(x_range, y_prob, color=color, linewidth=2, label=f'{category} Curve')


plt.axhline(0.5, color='gray', linestyle='--', linewidth=1)

plt.xlabel('Reward')
plt.ylabel('Probability of Taking Risk')
plt.title('Logistic Regression Curve: Reward vs Risk-Taking by Food Category')
plt.legend()
plt.show()